### ISSUE TITLE
Feature#2

### ISSUE THREAD

**Issue by enzowmosman** [EnzoWM02/MeusGastos#2]
Atualmente o botão de editar está duplicando a linha (provavelmente o if n ta funcionando conforme o esperado)

**Comment by enzowmosman** [comment]
Ao que tudo indica o problema ta na requisição PUT e na criação "dupla" que eu ignorei anteriormente do created_at

**Comment by Huio-op** [comment]
Seguinte, possivelmente criar um campo updatedAt vai fzr funcionar

**Comment by EnzoWM02** [comment]
Diversos ajustes foram feitos, incluindo alterar os campo createdAt e adicionado updatedAt.
O que corrigiu foi alterar, no método `updateGastos` de .save(gastos) para .save(currentGastos)
